apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-apps-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.ingressHost }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.services.middleware.name }}
            port:
              # TargetPort is the same as APP_BIND_PORT, the port on which the
              # service will send requests to, that your pod will be listening on.
              # matches MIDDLEWARE_SERVICE_TARGET_PORT in vertx deployment.
              number: 3000
        path: /
        pathType: Prefix
