apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-apps-ingress
  namespace: {{ .Values.namespace }}
spec:
  rules:
  - host: {{ .Values.appName }}
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.serviceName }}
            port:
              number: {{ .Values.serviceTargetPort }}
        path: /
        pathType: Prefix
